version: '2'

services:

  apigateway:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/apigateway
    container_name: mosaic-apigateway
    dns_search: .
    ports:
     - 80:80
    extra_hosts:
     - mosaic:${DOCKER_OUTER_HOST}

  db-mosaic:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/mosaic-postgres
    hostname: db-mosaic
    container_name: mosaic-postgres
    ports:
    - "5432:5432"

  mosaic:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/mosaic
    hostname: mosaic
    container_name: mosaic
    links:
     - db-mosaic:db
