version: '2'

services:

  apigateway:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/apigateway
    container_name: mosaic-apigateway
    dns_search: .
    ports:
     - 80:80
    extra_hosts:
     - mosaic:${DOCKER_OUTER_HOST}

  db-mosaic:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/mosaic-postgres
    hostname: db-mosaic
    container_name: mosaic-postgres
    ports:
    - 5432:5432

  geoserver-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geoserver-postgres
    hostname: geoserver-db
    container_name: mosaic-geoserver-db

  geoserver:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geoserver
    hostname: geoserver
    container_name: mosaic-geoserver
    links:
    - geoserver-db:db