version: '2'

services:

  apigateway:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/apigateway
    container_name: mosaic-apigateway
    dns_search: .
    ports:
     - 80:80
    extra_hosts:
     - mosaic:${DOCKER_OUTER_HOST}

  db-mosaic:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/mosaic-postgres
    hostname: db-mosaic
    container_name: mosaic-postgres
    ports:
    - 5432:5432

  geoserver-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geoserver-postgres
    hostname: geoserver-db
    container_name: mosaic-geoserver-db

  geoserver:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geoserver
    hostname: geoserver
    container_name: mosaic-geoserver
    links:
    - geoserver-db:db
    
  opendata-geowebcache:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/opendata-geowebcache
    hostname: opendata-geowebcache
    container_name: mosaic-opendata-geowebcache

  verkeersborden-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/verkeersborden-postgres
    hostname: verkeersborden-db
    container_name: mosaic-verkeersborden-db

  verkeersborden:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/verkeersborden
    hostname: verkeersborden
    container_name: mosaic-verkeersborden
    links:
    - verkeersborden-db:db

  geolatte-nosqlfs-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/nosql-postgres
    hostname: geolatte-nosqlfs-db
    container_name: mosaic-geolatte-nosqlfs-db

  geolatte-nosqlfs:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geolatte-nosqlfs
    hostname: geolatte-nosqlfs
    container_name: mosaic-geolatte-nosqlfs
    links:
    - geolatte-nosqlfs-db:db

  dataloader-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/dataloader-postgres
    hostname: dataloader-db
    container_name: mosaic-dataloader-db
    ports:
    - 5436:5432

  dataloader:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/dataloader
    hostname: dataloader
    container_name: mosaic-dataloader
    links:
    - dataloader-db:db

  geoloket-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geoloket-postgres
    hostname: db-geoloket
    container_name: mosaic-geoloket-db

  geoloket:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/geoloket
    hostname: geoloket
    container_name: mosaic-geoloket
    links:
    - geoloket-db:db

  thor-db:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/thor-postgres
    hostname: thor-db
    container_name: mosaic-thor-db

  thor:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/thor
    hostname: thor
    container_name: mosaic-thor
    links:
    - thor-db:db
