=== Gebruiker kan medewerkers opvragen

De gebruiker kan medewerkers opvragen o.b.v. een combinatie van input parameters

*Vereiste rechten:*

 * geen

*Input parameters:*

 * VoID (array)
 * VlimpersId (LDAP)
 * naam (bevat)
 * voornaam (bevat)
 * functie (bevat)
 * organisatiecode
 * vlag inclusief sub organisaties
 * Actief indicator
 * bron

*Antwoord:*

Het antwoord van de service bevat volgende gegevens :

 * VoID
 * VlimpersId
 * Naam
 * Voornaam
 * Functie
 * Organisatie
 * Niet-Actief aanduiding
 * bron

*Acceptatietesten:*

 * Als er geen input parameters ingevuld zijn, dan geeft de webservice de eerste 50 resultaten terug van alle WebIDM gebruikers en systeem gebruikers terug in het antwoord.
 * De gebruiker kan medewerkers opvragen o.b.v. één of meerdere VoID's.
 * De gebruiker kan een medewerker opvragen o.b.v. VlimpersID
 * De gebruiker kan medewerkers opvragen o.b.v. een gedeeltelijke naam.
 * De gebruiker kan medewerkers opvragen o.b.v. een gedeeltelijke voornaam.
 * De gebruiker kan medewerkers opvragen o.b.v. een gedeeltelijke functie.
 * De gebruiker kan medewerkers opvragen o.b.v. organisatie, al dan niet rekening houdend met sub-organisaties.
 * De gebruiker kan medewerkers opvragen o.b.v. actief indicator
 * De gebruiker kan medewerkers opvragen o.b.v. bron (WebIDM of PnO)
 * Als er geen gebruikers gevonden worden, geeft de webservice melding 'geen resultaat gevonden'
 * Als er een foutieve input parameter gegeven worden, geeft de webservice melding 'parameter <x> foutief'
 * Als er gebruikers gevonden worden, dan geeft de webservice de basisgegevens van deze gebruikers terug



