#%RAML 0.8
---
title: Geowebcache
version: v1

/rest/seed/{layer}:
  description: Seed een (deel van) een layer
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
            threadCount:
              type: integer
              required: true
            type:
              type: string
              required: true
              enum: ["truncate", "seed", "reseed"]
            gridSetId:
              type: string
              required: true
            format:
              type: string
              required: true
            zoomStart:
              type: integer
              required: true
            zoomStop:
              type: integer
              required: true
            minX:
              type: number
              required: true
            minY:
              type: number
              required: true
            maxX:
              type: number
              required: true
            maxY:
              type: number
              required: true
    responses:
      200:
        body:
          text/html:
