#%RAML 0.8
---
title: Mosaic
version: v1

schemas:
  - syncStatus:                        !include model/syncStatus.json
  - syncStatusResponse:                !include model/syncStatusResponse.json

traits:
  - acceptjson:                        !include traits/acceptjson.yaml

/syncstatus:
  !include syncstatus.raml
