# /rest/events/zi/verkeersborden/feed

/{page}:
  description: Feed van opstellingen

  uriParameters:
    page:
      description: Pagina van de feed
      type: string

  get:
    responses:
      200: