# /rest/zi

/verkeersborden/{id}:
  description: Vraag een opstelling op

  uriParameters:
    id:
      description: Id van de opstelling
      type: integer

  get:
    queryParameters:
      binaryData:
        displayName: binaryData
        description: Met binaire data? Zonder is sneller.
        type: boolean
        required: false
        repeat: false
    responses:
      200:
        body:
          application/vnd.awv.wdb-v3.0+json:
            schema: opstelling